### ISSUE TITLE
Scripts for Inference using your pre-trained models from Google Drive

### ISSUE THREAD

**Issue by dhingratul** [he-y/soft-filter-pruning#1]
Is the inference only scripts also available?

**Comment by he-y** [comment]
Please refer to scripts/inference_resnet.sh and the updated README.md

**Comment by dhingratul** [comment]
@he-y When you say "/path/to/ImageNet2012" , what is the structure of the folder, is the ILSVRC2012_img_train or val ?

**Comment by he-y** [comment]
We follow the Facebook process of ImageNet, please refer to [https://github.com/facebook/fb.resnet.torch/blob/master/INSTALL.md#download-the-imagenet-dataset](url).
Two subfolders ("train" and "val") are included in the "/path/to/ImageNet2012".
