### ISSUE TITLE
How to know the index of the first and last conv layer

### ISSUE THREAD

**Issue by raninbowlalala** [he-y/soft-filter-pruning#10]
Hello, I want to use your method in InceptionV3, which I download from https://download.pytorch.org/models/inception_v3_google-1a9a5a14.pth, but I don't know how to get the index of the first and last conv layer, could you help me?
Thank you very much!

**Comment by he-y** [comment]
Please refer the [code](https://github.com/he-y/soft-filter-pruning/blob/master/pruning_train.py#L437-L446).
`model.parameters()` could get the index and parameters of the network.
The conv layers have four dimensions, so you could find them with this condition.

**Comment by raninbowlalala** [comment]
Thank you! I have already found the index with your help.
