### ISSUE TITLE
how to obtain the pruned small model(inceptionv3)?

### ISSUE THREAD

**Issue by raninbowlalala** [he-y/soft-filter-pruning#11]
Hello, I use your method in InceptionV3, which I download from https://download.pytorch.org/models/inception_v3_google-1a9a5a14.pth. After 100 epoch train, I got the  best.inception_v3.pth.tar. Then I want to obtain the samll modle. I saw the issue [,](https://github.com/he-y/soft-filter-pruning/issues/10) but I still don't know how to obtain.
Can you help me?
Thank you!

**Comment by he-y** [comment]
Please refer to the [released pruned model](https://github.com/he-y/soft-filter-pruning/releases/tag/ResNet50_pruned) and [instruction](https://github.com/he-y/soft-filter-pruning#inference-the-pruned-model-without-zeros) for the model.
You can find the construction of pruned model [here](https://github.com/he-y/soft-filter-pruning/blob/master/models/imagenet_resnet_small.py).

**Comment by he-y** [comment]
Hi, we have released the conversion code to delete zeros and obtain small model, which might help you.

Please refer to the conversion code [here](https://github.com/he-y/soft-filter-pruning/blob/master/utils/get_small_model.py).
The corresponding explanation is [here](https://github.com/he-y/soft-filter-pruning#get-small-model).

**Comment by raninbowlalala** [comment]
I will try your code, thank you!

**Comment by zhanghongruiupup** [comment]
> 请参阅[发布修剪的模型](https://github.com/he-y/soft-filter-pruning/releases/tag/ResNet50_pruned)和[指令](https://github.com/he-y/soft-filter-pruning#inference-the-pruned-model-without-zeros)的模式。
> 您可以在[此处](https://github.com/he-y/soft-filter-pruning/blob/master/models/imagenet_resnet_small.py)找到修剪模型的构造。



> 请参阅[发布修剪的模型](https://github.com/he-y/soft-filter-pruning/releases/tag/ResNet50_pruned)和[指令](https://github.com/he-y/soft-filter-pruning#inference-the-pruned-model-without-zeros)的模式。
> 您可以在[此处](https://github.com/he-y/soft-filter-pruning/blob/master/models/imagenet_resnet_small.py)找到修剪模型的构造。

hi,resnet50_small error,Lack of index and bn_value
info:    
model = ResNet_small(Bottleneck, [3, 4, 6, 3], **kwargs)
TypeError: __init__() missing 2 required positional arguments: 'index' and 'bn_value'
