### ISSUE TITLE
How does this method accelerate training and predicting?

### ISSUE THREAD

**Issue by jimmyliu2013** [he-y/soft-filter-pruning#12]
Thank you for your excellent paper. 
But I don't understand why setting filters to zero can make it faster, since you still need to do the matrix multiplication. Could you please give me a brief explanation?
Thank you very much!

**Comment by he-y** [comment]
Please refer to the [released pruned model](https://github.com/he-y/soft-filter-pruning/releases/tag/ResNet50_pruned) and [instruction](https://github.com/he-y/soft-filter-pruning#inference-the-pruned-model-without-zeros) for the model.
You can find the construction of pruned model [here](https://github.com/he-y/soft-filter-pruning/blob/master/models/imagenet_resnet_small.py).

**Comment by jimmyliu2013** [comment]
Thank you for your time.
So we don't accelerate the training process, but after the training is finished, we remove all the zero-filters from the model so that the model is smaller and inference is faster. Am I right?

**Comment by he-y** [comment]
Yes, our paper is about accelerating the inference instead of the training.
