### ISSUE TITLE
what is the rule that to choose the skip list

### ISSUE THREAD

**Issue by ayoggchen** [he-y/soft-filter-pruning#13]
In pruning_train.py, the resnet50' total layers num is 150, but in code, the last layer's index is 159 which is out of range.
So I wonder what is the rule to choose the skip layer?
Thanks.

**Comment by ayoggchen** [comment]
And what is the mean of mask_index?

**Comment by he-y** [comment]
skip layer is the downsampling layer.

last_index = 159 is the index of fc layer, so we could prune conv layers via [this line](https://github.com/he-y/soft-filter-pruning/blob/master/pruning_train.py#L490).

mask_index is the index of the pruned filter in 1-dimension.

**Comment by ayoggchen** [comment]
> skip layer is the downsampling layer.
> 
> last_index = 159 is the index of fc layer, so we could prune conv layers via [this line](https://github.com/he-y/soft-filter-pruning/blob/master/pruning_train.py#L490).
> 
> mask_index is the index of the pruned filter in 1-dimension.

Yes, I know this parameters literally. But when I checked these layer, I found that these layer were not exactly the layer you want to skip. And ALSO, fc layer's number is not what you list in that file. So I wonder which version of the resnet do you use? Is it the origin version in pytorchvision? (I thought it was the origin vision which is you include in your code, but that version can not correspond to what I mention above).
Thanks!

**Comment by he-y** [comment]
Please provide your detailed results here. 
My model is same to official torchvision model.
