### ISSUE TITLE
zero_model and non-zero_model

### ISSUE THREAD

**Issue by yyx1107** [he-y/soft-filter-pruning#14]
Only remove the zero filters can the model be faster and smaller.I  am wondering  if the precision is different between the zero model and non-zero model?

**Comment by he-y** [comment]
The accuracy of the zero model and non-zero model are the same.
Please refer to the [released model](https://github.com/he-y/soft-filter-pruning/releases).

**Comment by yyx1107** [comment]
> The accuracy of the zero model and non-zero model are the same.
> Please refer to the [released model](https://github.com/he-y/soft-filter-pruning/releases).

Thank you !
