### ISSUE TITLE
Just train from scratch with the pruning rate

### ISSUE THREAD

**Issue by ShoufaChen** [he-y/soft-filter-pruning#15]
Hi He Yang,

Thanks for your contribution of the paper and code.

I wonder have you ever do such a experiment:

multiply every convolution layers of ResNet with the pruning rate (e.g. 0.7)  and then train the squeezed model from scratch on ImageNet ?

Thanks.

**Comment by he-y** [comment]
I have not done the experiment.
But you can take a look at [this paper](https://openreview.net/forum?id=rJlnB3C5Ym).

**Comment by ShoufaChen** [comment]
thank you for your quick reply :)
