### ISSUE TITLE
Question for FLOPs calculation

### ISSUE THREAD

**Issue by gaomingqi** [he-y/soft-filter-pruning#16]
Hi He Yang

Thanks for sharing your amazing research work 

Could you give more detailed information about the FLOPs calculation process?

I see cifar_resnet_flop.py is only for resent, so could you provide VGG version?

Many Thanks

Best Regards

**Comment by he-y** [comment]
Thanks for your interest.
You can take a look at [Netscope](http://dgschwend.github.io/netscope/#/preset/vgg-16) and [FLOP Calculator](https://github.com/Lyken17/pytorch-OpCounter).
