### ISSUE TITLE
how to obtain the pruned new model?

### ISSUE THREAD

**Issue by lith0613** [he-y/soft-filter-pruning#2]
The code just use a mask to replace the pruned filters, but how to get the real pruned model ? 
Besides, can your share your method about how to calculate the flops of your work ?

**Comment by he-y** [comment]
you could refer to the [code](https://github.com/he-y/soft-filter-pruning/blob/master/models/imagenet_resnet_small.py) to get the detailed structure of the pruned model. I will check and update the conversion code as soon as possible.

**Comment by lith0613** [comment]
I see the code of imagenet_resnet_small, but these functions are not called in other files. I don't know what is meaning of the parameters in these functions.  Can you make a explanation about them?  Thank you !

**Comment by he-y** [comment]
Please refer to the [released pruned model](https://github.com/he-y/soft-filter-pruning/releases/tag/ResNet50_pruned) and [instruction](https://github.com/he-y/soft-filter-pruning#inference-the-pruned-model-without-zeros) for the model.

**Comment by Ariel-JUAN** [comment]
@he-y Hi, will you release getting the real pruned model codes?

**Comment by lith0613** [comment]
> Please refer to the [released pruned model](https://github.com/he-y/soft-filter-pruning/releases/tag/ResNet50_pruned) and [instruction](https://github.com/he-y/soft-filter-pruning#inference-the-pruned-model-without-zeros) for the model.
> You can find the construction of pruned model [here](https://github.com/he-y/soft-filter-pruning/blob/master/models/imagenet_resnet_small.py).

hi, He, I am sorry to bother you again.
I still haven't got the details about how to use your zero-model to obtain the without-zero model. Although I found and tested your released compact ResNet-50 model. But I want to know the details about how to use your zero-model to get the without-zero model,  for other model such as ResNet-34. Can you give a example code. I don't know how to use your small model code, because these functions are not called in other files.

**Comment by he-y** [comment]
Hi, sorry for the delay code release.
Please refer to the conversion code [here](https://github.com/he-y/soft-filter-pruning/blob/master/utils/get_small_model.py).
The corresponding explanation is [here](https://github.com/he-y/soft-filter-pruning#get-small-model).

**Comment by lith0613** [comment]
> Hi, sorry for the delay code release.
> Please refer to the conversion code [here](https://github.com/he-y/soft-filter-pruning/blob/master/utils/get_small_model.py).
> The corresponding explanation is [here](https://github.com/he-y/soft-filter-pruning#get-small-model).

Thanks so much ! I test the code, but the script run error in ResNet34 and ResNet18, looking forward to your update !

**Comment by TheLostIn** [comment]
> > Hi, sorry for the delay code release.
> > Please refer to the conversion code [here](https://github.com/he-y/soft-filter-pruning/blob/master/utils/get_small_model.py).
> > The corresponding explanation is [here](https://github.com/he-y/soft-filter-pruning#get-small-model).
> 
> Thanks so much ! I test the code, but the script run error in ResNet34 and ResNet18, looking forward to your update !

Hi,I test ResNet18,failed too,
I also want to know what the use of 5 in line 282 `for x in range(0, len(item) - 2, 5)`.
Have you solved it?

**Comment by xuzhuang1996** [comment]
> > > Hi, sorry for the delay code release.
> > > Please refer to the conversion code [here](https://github.com/he-y/soft-filter-pruning/blob/master/utils/get_small_model.py).
> > > The corresponding explanation is [here](https://github.com/he-y/soft-filter-pruning#get-small-model).
> > 
> > 
> > Thanks so much ! I test the code, but the script run error in ResNet34 and ResNet18, looking forward to your update !
> 
> Hi,I test ResNet18,failed too, I also want to know what the use of 5 in line 282 `for x in range(0, len(item) - 2, 5)`. Have you solved it?

Have you solved it? how to use your zero-model to obtain the without-zero model.
