### ISSUE TITLE
有压缩后的模型吗

### ISSUE THREAD

**Issue by Zeitzmz** [he-y/soft-filter-pruning#3]
您好，文章裁剪的思路很赞。
请问有ｓｏｆｔｐｒｕｎｉｎｇ训练到最后，裁剪掉通道的模型吗？
我仔细看了代码，觉得代码裁剪ｒｅｓｎｅｔ到最后，并没法裁剪掉所有应该裁剪的通道，因为ｒｅｓｎｅｔ模块很多卷基层存在相关性，训练时可能存在通道错位情况，并没法最终裁剪。

**Comment by he-y** [comment]
Hi, we have released the conversion code to delete zeros and obtain the small model, which might help you.

Please refer to the conversion code [here](https://github.com/he-y/soft-filter-pruning/blob/master/utils/get_small_model.py).
The corresponding explanation is [here](https://github.com/he-y/soft-filter-pruning#get-small-model).
