### ISSUE TITLE
缺少pruning_train_from_pretrain.py代码

### ISSUE THREAD

**Issue by 18463105800** [he-y/soft-filter-pruning#4]
你好，首先谢谢你提供的代码。但我想问的是是不是少了最后一个实际剪枝的代码pruning_train_from_pretrain.py，如果能够提供那再好不过了，谢谢。

**Comment by he-y** [comment]
Please refer to the [released pruned model](https://github.com/he-y/soft-filter-pruning/releases/tag/ResNet50_pruned) and [instruction](https://github.com/he-y/soft-filter-pruning#inference-the-pruned-model-without-zeros) for the model.

**Comment by 18463105800** [comment]
Thank you for your reply.

**Comment by ANUSHAJAY** [comment]
Hello, I must thank you for sharing your good work with us.
I however have one question about the implementation(same as mentioned above).
I am trying to perform pruning on a pretrained model. In one of your scripts it has been given as:
python pruning_train_from_pretrain.py $DOME_HOME/datasets/ILSVRC2012 -a resnet18 --save_dir ./snapshots/Pretrain-resnet18-rate-0.7 --rate 0.7 --layer_begin 0 --layer_end 57 --layer_inter 3 --workers 36 --use_pretrain --lr 0.01
However, there are a couple of problems here:
error: unrecognized arguments: --use_pretrain --lr 0.01
Also, I don't understand how to incorporate the "use_pretrain" in my code.
I am also unable to find "pruning_train_from_pretrain.py" in your repository. The link you have shared does not contain the file I mentioned.
I would be much obliged if you could help me with this.
Keep up the good work!
Thanks in advance
