### ISSUE TITLE
How to preserve non-zero filters???

### ISSUE THREAD

**Issue by linyuanze** [he-y/soft-filter-pruning#5]
Thanks for your wonderful work, but I'm wondering how can I preserve finally compact model.

**Comment by he-y** [comment]
Please refer to the [issue](https://github.com/he-y/soft-filter-pruning/issues/2), which is similar to your proposed question.

**Comment by linyuanze** [comment]
Then have you test the compressed model under object detection algorithms(such as SSD, faster R-CNN etc) ???

**Comment by he-y** [comment]
No, we focus on the classification problem in this paper.

**Comment by yyx1107** [comment]
> Then have you test the compressed model under object detection algorithms(such as SSD, faster R-CNN etc) ???

Hi, have you try this?

**Comment by he-y** [comment]
@yyx1107 
No. We focus on the image classification task.
