### ISSUE TITLE
How to deal with parameters in BN layer?

### ISSUE THREAD

**Issue by dawuchen** [he-y/soft-filter-pruning#6]
In your code ,you only zeroize the parameter of conv layer. But there are also parameters in BN(scaling and bias, especially the latter) layer, the output of BN will still be non-zero although its input is zero. Whether it would be better to zeroize the param in BN?

**Comment by he-y** [comment]
If the input is zero, the output of BN could be calculated in advance and saved, see the [corresponding code](https://github.com/he-y/soft-filter-pruning/blob/master/models/imagenet_resnet_small.py#L180-L183). Then it would have little effect on the inference process.

In the meanwhile, to conduct elementwise summation with shortcut and conv_output (see the picture below), the [indices of the remaining channel](https://github.com/he-y/soft-filter-pruning/blob/master/models/imagenet_resnet_small.py#L176-L179) are saved.

![image](https://user-images.githubusercontent.com/10541284/52170588-2d9d1d00-27a1-11e9-8ea5-86a8a3f0619c.png)

In this paper, we focus on pruning conv layers. It works both for the network with and without BN layer.
Some previous methods focus on scaling factor of BN layer, which is not suitable for structure without BN layer.
