### ISSUE TITLE
How to deal with the situation where there is not enough zero filters?

### ISSUE THREAD

**Issue by lkyf** [he-y/soft-filter-pruning#8]
If we cannot obtain N_{i+1}(1-P_{i}) zero filters at layer i in the converged network. How to deal with it?

**Comment by he-y** [comment]
Assume we have 64 filters in the network.
If the pruning rate is 30%, we select 19 filters with small L2-norm and prune them, in other words, we change all the value of those 19 filters to zero.
If we set a threshold, we could always find them.
