### ISSUE TITLE
How to install torchvision0.3.0?

### ISSUE THREAD

**Issue by raninbowlalala** [he-y/soft-filter-pruning#9]
I used command "pip3 install torch==0.3.1" successfully, but when I used "pip3 install torchvision==0.3.0", the error log is as below:
```
Could not find a version that satisfies the requirement torchvision==0.3.0 (from versions: 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.2.0, 0.2.1, 0.2.2, 0.2.2.post2, 0.2.2.post3)
No matching distribution found for torchvision==0.3.0
```

Then I go to https://github.com/pytorch/vision, but I found the latest release version is 0.2.2. So I wonder how to install toechvision?
Thanks!

**Comment by he-y** [comment]
Hi, sorry for the typo.
The version of torchvision should be 0.2.0.
I have fixed the errors in README.

**Comment by raninbowlalala** [comment]
ok, thank you! I will try 0.2.0.
